spring:
  config:
    activate:
      on-profile: dev

  # 로컬 개발에서는 중앙 Config/Kubernetes를 사용하지 않는다.
  cloud:
    kubernetes:
      discovery:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db?currentSchema=notification&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

server:
  port: ${SERVER_PORT:9004}

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    site.yesaido.notification_server: DEBUG
