-- Notification Service 전용 PostgreSQL 스키마
-- Auth/Cultivation 등 다른 서비스의 테이블은 직접 참조하지 않는다.

CREATE TABLE channel_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(30)  NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    is_deleted   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_channel_type_code UNIQUE (code)
);

CREATE TABLE subscription_target_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type  VARCHAR(30)  NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_subscription_target_type_code UNIQUE (target_type)
);

CREATE TABLE notification_event_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL,
    display_name VARCHAR(150) NOT NULL,
    description  VARCHAR(500),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    target_type  BIGINT       NOT NULL,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_event_type_target_type
        FOREIGN KEY (target_type)
        REFERENCES subscription_target_type (id),
    CONSTRAINT uq_notification_event_type_code UNIQUE (code)
);

CREATE TABLE notification_subscription_type (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_event_type_id BIGINT       NOT NULL,
    subscription_target_type_id BIGINT       NOT NULL,
    notification_subscription_name VARCHAR(20) NOT NULL,
    description              VARCHAR(500),
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscription_type_event
        FOREIGN KEY (notification_event_type_id)
        REFERENCES notification_event_type (id),
    CONSTRAINT fk_subscription_type_target
        FOREIGN KEY (subscription_target_type_id)
        REFERENCES subscription_target_type (id),
    CONSTRAINT uq_subscription_type_event_target
        UNIQUE (notification_event_type_id, subscription_target_type_id)
);

CREATE TABLE subscription_channel (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_subscription_type_id BIGINT NOT NULL,
    channel_type_id                 BIGINT NOT NULL,
    created_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscription_channel_subscription_type
        FOREIGN KEY (notification_subscription_type_id)
        REFERENCES notification_subscription_type (id),
    CONSTRAINT fk_subscription_channel_channel_type
        FOREIGN KEY (channel_type_id)
        REFERENCES channel_type (id),
    CONSTRAINT uq_subscription_channel
        UNIQUE (notification_subscription_type_id, channel_type_id)
);

CREATE TABLE notification_template (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_event_type_id BIGINT       NOT NULL,
    channel_type_id          BIGINT       NOT NULL,
    body_template            TEXT         NOT NULL,
    version                  INTEGER      NOT NULL,
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_template_event
        FOREIGN KEY (notification_event_type_id)
        REFERENCES notification_event_type (id),
    CONSTRAINT fk_template_channel
        FOREIGN KEY (channel_type_id)
        REFERENCES channel_type (id),
    CONSTRAINT uq_template_event_channel_version
        UNIQUE (notification_event_type_id, channel_type_id, version)
);

CREATE TABLE notification_endpoint (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    channel_type_id BIGINT      NOT NULL,
    display_name   VARCHAR(100) NOT NULL,
    destination   VARCHAR(500) NOT NULL,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_endpoint_channel
        FOREIGN KEY (channel_type_id)
        REFERENCES channel_type (id)
);

CREATE TABLE notification_subscription (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_subscription_type_id BIGINT NOT NULL,
    notification_endpoint_id        BIGINT NOT NULL,
    target_id                       BIGINT NOT NULL,
    enabled                         BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted                      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscription_type
        FOREIGN KEY (notification_subscription_type_id)
        REFERENCES notification_subscription_type (id),
    CONSTRAINT fk_subscription_endpoint
        FOREIGN KEY (notification_endpoint_id)
        REFERENCES notification_endpoint (id)
);

CREATE TABLE notification (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_template_id BIGINT      NOT NULL,
    source_event_id       UUID           NOT NULL,
    event_payload         JSONB          NOT NULL,
    message               TEXT           NOT NULL,
    created_at            TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_notification_source_event UNIQUE (source_event_id),
    CONSTRAINT fk_notification_template
        FOREIGN KEY (notification_template_id)
        REFERENCES notification_template (id)
);

CREATE TABLE notification_delivery (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id             BIGINT       NOT NULL,
    notification_subscription_id BIGINT      NOT NULL,
    status                      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    provider_message_id         VARCHAR(200),
    rendered_message            TEXT         NOT NULL,
    attempt_count               SMALLINT     NOT NULL DEFAULT 0,
    error                       TEXT,
    sent_at                     TIMESTAMP,
    created_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_delivery_notification
        FOREIGN KEY (notification_id)
        REFERENCES notification (id),
    CONSTRAINT fk_delivery_subscription
        FOREIGN KEY (notification_subscription_id)
        REFERENCES notification_subscription (id),
    CONSTRAINT chk_delivery_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT chk_delivery_attempt_count
        CHECK (attempt_count BETWEEN 0 AND 3),
    CONSTRAINT uq_delivery_notification_subscription
        UNIQUE (notification_id, notification_subscription_id)
);

-- 활성 구독만 중복을 막고, 소프트 삭제된 과거 이력은 보존한다.
CREATE UNIQUE INDEX uq_active_notification_subscription
    ON notification_subscription (
        notification_subscription_type_id,
        notification_endpoint_id,
        target_id
    )
    WHERE is_deleted = FALSE;

CREATE INDEX idx_notification_created
    ON notification (created_at DESC);

CREATE INDEX idx_notification_delivery_status
    ON notification_delivery (status, updated_at);

CREATE INDEX idx_endpoint_user_enabled
    ON notification_endpoint (user_id, enabled);
